export const SET_LOCALISATION = "SET_LOCALISATION";
export const SET_SETTING = "SET_SETTING";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_IS_PRESS = "SET_IS_PRESS";
export const SYNCHRO_SETTING_TEMP = "SYNCHRO_SETTING_TEMP";
