export const SET_LOCATION = "SET_LOCATION";
export const SET_SETTING = "SET_SETTING";
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_IS_PRESS = "SET_IS_PRESS";
export const SYNCHRO_SETTING = "SYNCHRO_SETTING";
export const SYNCHRO_SETTING_INIT = "SYNCHRO_SETTING_INIT";
